/** Domain module barrel — dependency order: common → domains → project. */
export * from './common.js'
export * from './scene.js'
export * from './material.js'
export * from './prefab.js'
export * from './animation.js'
export * from './particle.js'
export * from './project.js'
export * from './material-graph.js'
export * from './animation-clip.js'
export * from './animator-v2.js'
